// countryDialCodes.js
// Tento súbor obsahuje globálny zoznam predvolieb pre formátovanie telefónnych čísel.

// Zoznam predvolieb s pridanými názvami krajín, zoradený zostupne podľa dĺžky pre správne rozpoznávanie
// Pripojenie tohto súboru do <head> HTML súboru sprístupní tento zoznam globálne.
export const countryDialCodes = [
    { name: 'Slovensko', code: 'SK', dialCode: '+421' },
    { name: 'Česká republika', code: 'CZ', dialCode: '+420' },
    { name: 'Spojené štáty', code: 'US', dialCode: '+1' },
    { name: 'Kanada', code: 'CA', dialCode: '+1' },
    { name: 'Rusko', code: 'RU', dialCode: '+7' },
    { name: 'Egypt', code: 'EG', dialCode: '+20' },
    { name: 'Južná Afrika', code: 'ZA', dialCode: '+27' },
    { name: 'Grécko', code: 'GR', dialCode: '+30' },
    { name: 'Holandsko', code: 'NL', dialCode: '+31' },
    { name: 'Belgicko', code: 'BE', dialCode: '+32' },
    { name: 'Francúzsko', code: 'FR', dialCode: '+33' },
    { name: 'Španielsko', code: 'ES', dialCode: '+34' },
    { name: 'Gibraltár', code: 'GI', dialCode: '+350' },
    { name: 'Portugalsko', code: 'PT', dialCode: '+351' },
    { name: 'Írsko', code: 'IE', dialCode: '+353' },
    { name: 'Island', code: 'IS', dialCode: '+354' },
    { name: 'Albánsko', code: 'AL', dialCode: '+355' },
    { name: 'Malta', code: 'MT', dialCode: '+356' },
    { name: 'Cyprus', code: 'CY', dialCode: '+357' },
    { name: 'Fínsko', code: 'FI', dialCode: '+358' },
    { name: 'Bulharsko', code: 'BG', dialCode: '+359' },
    { name: 'Litva', code: 'LT', dialCode: '+370' },
    { name: 'Lotyšsko', code: 'LV', dialCode: '+371' },
    { name: 'Estónsko', code: 'EE', dialCode: '+372' },
    { name: 'Moldavsko', code: 'MD', dialCode: '+373' },
    { name: 'Arménsko', code: 'AM', dialCode: '+374' },
    { name: 'Bielorusko', code: 'BY', dialCode: '+375' },
    { name: 'Andorra', code: 'AD', dialCode: '+376' },
    { name: 'Monako', code: 'MC', dialCode: '+377' },
    { name: 'San Maríno', code: 'SM', dialCode: '+378' },
    { name: 'Ukrajina', code: 'UA', dialCode: '+380' },
    { name: 'Srbsko', code: 'RS', dialCode: '+381' },
    { name: 'Čierna Hora', code: 'ME', dialCode: '+382' },
    { name: 'Kosovo', code: 'XK', dialCode: '+383' },
    { name: 'Chorvátsko', code: 'HR', dialCode: '+385' },
    { name: 'Slovinsko', code: 'SI', dialCode: '+386' },
    { name: 'Bosna a Hercegovina', code: 'BA', dialCode: '+387' },
    { name: 'Severné Macedónsko', code: 'MK', dialCode: '+389' },
    { name: 'Lichtenštajnsko', code: 'LI', dialCode: '+423' },
    { name: 'Rakúsko', code: 'AT', dialCode: '+43' },
    { name: 'Spojené kráľovstvo', code: 'GB', dialCode: '+44' },
    { name: 'Dánsko', code: 'DK', dialCode: '+45' },
    { name: 'Švédsko', code: 'SE', dialCode: '+46' },
    { name: 'Nórsko', code: 'NO', dialCode: '+47' },
    { name: 'Poľsko', code: 'PL', dialCode: '+48' },
    { name: 'Nemecko', code: 'DE', dialCode: '+49' },
    { name: 'Peru', code: 'PE', dialCode: '+51' },
    { name: 'Mexiko', code: 'MX', dialCode: '+52' },
    { name: 'Kuba', code: 'CU', dialCode: '+53' },
    { name: 'Argentína', code: 'AR', dialCode: '+54' },
    { name: 'Brazília', code: 'BR', dialCode: '+55' },
    { name: 'Čile', code: 'CL', dialCode: '+56' },
    { name: 'Kolumbia', code: 'CO', dialCode: '+57' },
    { name: 'Venezuela', code: 'VE', dialCode: '+58' },
    { name: 'Malajzia', code: 'MY', dialCode: '+60' },
    { name: 'Austrália', code: 'AU', dialCode: '+61' },
    { name: 'Indonézia', code: 'ID', dialCode: '+62' },
    { name: 'Filipíny', code: 'PH', dialCode: '+63' },
    { name: 'Nový Zéland', code: 'NZ', dialCode: '+64' },
    { name: 'Singapur', code: 'SG', dialCode: '+65' },
    { name: 'Thajsko', code: 'TH', dialCode: '+66' },
    { name: 'Japonsko', code: 'JP', dialCode: '+81' },
    { name: 'Južná Kórea', code: 'KR', dialCode: '+82' },
    { name: 'Vietnam', code: 'VN', dialCode: '+84' },
    { name: 'Čína', code: 'CN', dialCode: '+86' },
    { name: 'Turecko', code: 'TR', dialCode: '+90' },
    { name: 'India', code: 'IN', dialCode: '+91' },
    { name: 'Pakistan', code: 'PK', dialCode: '+92' },
    { name: 'Afganistan', code: 'AF', dialCode: '+93' },
    { name: 'Srí Lanka', code: 'LK', dialCode: '+94' },
    { name: 'Mjanmarsko', code: 'MM', dialCode: '+95' },
    { name: 'Irán', code: 'IR', dialCode: '+98' },
    { name: 'Sýria', code: 'SY', dialCode: '+963' },
    { name: 'Irak', code: 'IQ', dialCode: '+964' },
    { name: 'Kuvajt', code: 'KW', dialCode: '+965' },
    { name: 'Saudská Arábia', code: 'SA', dialCode: '+966' },
    { name: 'Jemen', code: 'YE', dialCode: '+967' },
    { name: 'Omán', code: 'OM', dialCode: '+968' },
    { name: 'Palestína', code: 'PS', dialCode: '+970' },
    { name: 'Spojené arabské emiráty', code: 'AE', dialCode: '+971' },
    { name: 'Libanon', code: 'LB', dialCode: '+961' },
    { name: 'Jordánsko', code: 'JO', dialCode: '+962' },
    { name: 'Izrael', code: 'IL', dialCode: '+972' },
    { name: 'Bahrajn', code: 'BH', dialCode: '+973' },
    { name: 'Katar', code: 'QA', dialCode: '+974' },
    { name: 'Bhután', code: 'BT', dialCode: '+975' },
    { name: 'Mongolsko', code: 'MN', dialCode: '+976' },
    { name: 'Nepál', code: 'NP', dialCode: '+977' },
    { name: 'Kazachstan', code: 'KZ', dialCode: '+76' },
    { name: 'Tadžikistan', code: 'TJ', dialCode: '+992' },
    { name: 'Turkménsko', code: 'TM', dialCode: '+993' },
    { name: 'Uzbekistan', code: 'UZ', dialCode: '+998' },
    { name: 'Azerbajdžan', code: 'AZ', dialCode: '+994' },
    { name: 'Gruzínsko', code: 'GE', dialCode: '+995' },
    { name: 'Kirgizsko', code: 'KG', dialCode: '+996' },
    { name: 'Hongkong', code: 'HK', dialCode: '+852' },
    { name: 'Macao', code: 'MO', dialCode: '+853' },
    { name: 'Kambodža', code: 'KH', dialCode: '+855' },
    { name: 'Laos', code: 'LA', dialCode: '+856' },
    { name: 'Severná Kórea', code: 'KP', dialCode: '+850' },
    { name: 'Haiti', code: 'HT', dialCode: '+509' },
    { name: 'Honduras', code: 'HN', dialCode: '+504' },
    { name: 'Guatemala', code: 'GT', dialCode: '+502' },
    { name: 'Salvádor', code: 'SV', dialCode: '+503' },
    { name: 'Nikaragua', code: 'NI', dialCode: '+505' },
    { name: 'Kostarika', code: 'CR', dialCode: '+506' },
    { name: 'Panama', code: 'PA', dialCode: '+507' },
    { name: 'Saint-Pierre a Miquelon', code: 'PM', dialCode: '+508' },
    { name: 'Jamajka', code: 'JM', dialCode: '+1876' },
    { name: 'Barbados', code: 'BB', dialCode: '+1246' },
    { name: 'Bahamy', code: 'BS', dialCode: '+1242' },
    { name: 'Antigua a Barbuda', code: 'AG', dialCode: '+1268' },
    { name: 'Britské Panenské ostrovy', code: 'VG', dialCode: '+1284' },
    { name: 'Kajmanie ostrovy', code: 'KY', dialCode: '+1345' },
    { name: 'Bermudy', code: 'BM', dialCode: '+1441' },
    { name: 'Grenada', code: 'GD', dialCode: '+1473' },
    { name: 'Turks a Caicos', code: 'TC', dialCode: '+1649' },
    { name: 'Montserrat', code: 'MS', dialCode: '+1664' },
    { name: 'Severné Mariány', code: 'MP', dialCode: '+1670' },
    { name: 'Guam', code: 'GU', dialCode: '+1671' },
    { name: 'Americké Panenské ostrovy', code: 'VI', dialCode: '+1340' },
    { name: 'Svätý Krištof a Nevis', code: 'KN', dialCode: '+1869' },
    { name: 'Svätá Lucia', code: 'LC', dialCode: '+1758' },
    { name: 'Svätý Vincent a Grenadíny', code: 'VC', dialCode: '+1784' },
    { name: 'Dominika', code: 'DM', dialCode: '+1767' },
    { name: 'Dominikánska republika', code: 'DO', dialCode: '+1809' },
    { name: 'Portoriko', code: 'PR', dialCode: '+1787' },
    { name: 'Trinidad a Tobago', code: 'TT', dialCode: '+1868' },
    { name: 'Anguilla', code: 'AI', dialCode: '+1264' },
    { name: 'Aruba', code: 'AW', dialCode: '+297' },
    { name: 'Bahrajn', code: 'BH', dialCode: '+973' },
    { name: 'Bangladéš', code: 'BD', dialCode: '+880' },
    { name: 'Belize', code: 'BZ', dialCode: '+501' },
    { name: 'Benin', code: 'BJ', dialCode: '+229' },
    { name: 'Bermudy', code: 'BM', dialCode: '+1441' },
    { name: 'Bolívia', code: 'BO', dialCode: '+591' },
    { name: 'Botswana', code: 'BW', dialCode: '+267' },
    { name: 'Brunej', code: 'BN', dialCode: '+673' },
    { name: 'Burkina Faso', code: 'BF', dialCode: '+226' },
    { name: 'Burundi', code: 'BI', dialCode: '+257' },
    { name: 'Kamerun', code: 'CM', dialCode: '+237' },
    { name: 'Stredoafrická republika', code: 'CF', dialCode: '+236' },
    { name: 'Čad', code: 'TD', dialCode: '+235' },
    { name: 'Comory', code: 'KM', dialCode: '+269' },
    { name: 'Kongo-Brazzaville', code: 'CG', dialCode: '+242' },
    { name: 'Kongo-Kinshasa', code: 'CD', dialCode: '+243' },
    { name: 'Pobrežie Slonoviny', code: 'CI', dialCode: '+225' },
    { name: 'Džibutsko', code: 'DJ', dialCode: '+253' },
    { name: 'Východný Timor', code: 'TL', dialCode: '+670' },
    { name: 'Rovníková Guinea', code: 'GQ', dialCode: '+240' },
    { name: 'Eritrea', code: 'ER', dialCode: '+291' },
    { name: 'Etiópia', code: 'ET', dialCode: '+251' },
    { name: 'Fidži', code: 'FJ', dialCode: '+679' },
    { name: 'Francúzska Guyana', code: 'GF', dialCode: '+594' },
    { name: 'Francúzska Polynézia', code: 'PF', dialCode: '+689' },
    { name: 'Gabon', code: 'GA', dialCode: '+241' },
    { name: 'Gambia', code: 'GM', dialCode: '+220' },
    { name: 'Ghana', code: 'GH', dialCode: '+233' },
    { name: 'Guinea', code: 'GN', dialCode: '+224' },
    { name: 'Guinea-Bissau', code: 'GW', dialCode: '+245' },
    { name: 'Guyana', code: 'GY', dialCode: '+592' },
    { name: 'Maďarsko', code: 'HU', dialCode: '+36' },
    { name: 'India', code: 'IN', dialCode: '+91' },
    { name: 'Indonézia', code: 'ID', dialCode: '+62' },
    { name: 'Irak', code: 'IQ', dialCode: '+964' },
    { name: 'Izrael', code: 'IL', dialCode: '+972' },
    { name: 'Jordánsko', code: 'JO', dialCode: '+962' },
    { name: 'Keňa', code: 'KE', dialCode: '+254' },
    { name: 'Kiribati', code: 'KI', dialCode: '+686' },
    { name: 'Kórea, Severná', code: 'KP', dialCode: '+850' },
    { name: 'Kórea, Južná', code: 'KR', dialCode: '+82' },
    { name: 'Kostarika', code: 'CR', dialCode: '+506' },
    { name: 'Kuvajt', code: 'KW', dialCode: '+965' },
    { name: 'Laos', code: 'LA', dialCode: '+856' },
    { name: 'Libanon', code: 'LB', dialCode: '+961' },
    { name: 'Libéria', code: 'LR', dialCode: '+231' },
    { name: 'Líbya', code: 'LY', dialCode: '+218' },
    { name: 'Lichtenštajnsko', code: 'LI', dialCode: '+423' },
    { name: 'Luxembursko', code: 'LU', dialCode: '+352' },
    { name: 'Macao', code: 'MO', dialCode: '+853' },
    { name: 'Macedónsko, Republika', code: 'MK', dialCode: '+389' },
    { name: 'Madagaskar', code: 'MG', dialCode: '+261' },
    { name: 'Malawi', code: 'MW', dialCode: '+265' },
    { name: 'Malajzia', code: 'MY', dialCode: '+60' },
    { name: 'Maldivy', code: 'MV', dialCode: '+960' },
    { name: 'Mali', code: 'ML', dialCode: '+223' },
    { name: 'Malta', code: 'MT', dialCode: '+356' },
    { name: 'Marshallove ostrovy', code: 'MH', dialCode: '+692' },
    { name: 'Mauritánia', code: 'MR', dialCode: '+222' },
    { name: 'Maurícius', code: 'MU', dialCode: '+230' },
    { name: 'Mexiko', code: 'MX', dialCode: '+52' },
    { name: 'Mikronézia', code: 'FM', dialCode: '+691' },
    { name: 'Moldavsko', code: 'MD', dialCode: '+373' },
    { name: 'Monako', code: 'MC', dialCode: '+377' },
    { name: 'Mongolsko', code: 'MN', dialCode: '+976' },
    { name: 'Montserrat', code: 'MS', dialCode: '+1664' },
    { name: 'Maroko', code: 'MA', dialCode: '+212' },
    { name: 'Mozambik', code: 'MZ', dialCode: '+258' },
    { name: 'Mjanmarsko', code: 'MM', dialCode: '+95' },
    { name: 'Namíbia', code: 'NA', dialCode: '+264' },
    { name: 'Nauru', code: 'NR', dialCode: '+674' },
    { name: 'Nepál', code: 'NP', dialCode: '+977' },
    { name: 'Holandsko', code: 'NL', dialCode: '+31' },
    { name: 'Nová Kaledónia', code: 'NC', dialCode: '+687' },
    { name: 'Nový Zéland', code: 'NZ', dialCode: '+64' },
    { name: 'Nikaragua', code: 'NI', dialCode: '+505' },
    { name: 'Niger', code: 'NE', dialCode: '+227' },
    { name: 'Nigéria', code: 'NG', dialCode: '+234' },
    { name: 'Niue', code: 'NU', dialCode: '+683' },
    { name: 'Nórsko', code: 'NO', dialCode: '+47' },
    { name: 'Omán', code: 'OM', dialCode: '+968' },
    { name: 'Pakistan', code: 'PK', dialCode: '+92' },
    { name: 'Palau', code: 'PW', dialCode: '+680' },
    { name: 'Panama', code: 'PA', dialCode: '+507' },
    { name: 'Papua-Nová Guinea', code: 'PG', dialCode: '+675' },
    { name: 'Paraguaj', code: 'PY', dialCode: '+595' },
    { name: 'Peru', code: 'PE', dialCode: '+51' },
    { name: 'Filipíny', code: 'PH', dialCode: '+63' },
    { name: 'Poľsko', code: 'PL', dialCode: '+48' },
    { name: 'Portugalsko', code: 'PT', dialCode: '+351' },
    { name: 'Portoriko', code: 'PR', dialCode: '+1787' },
    { name: 'Katar', code: 'QA', dialCode: '+974' },
    { name: 'Réunion', code: 'RE', dialCode: '+262' },
    { name: 'Rumunsko', code: 'RO', dialCode: '+40' },
    { name: 'Rusko', code: 'RU', dialCode: '+7' },
    { name: 'Rwanda', code: 'RW', dialCode: '+250' },
    { name: 'Samoa', code: 'WS', dialCode: '+685' },
    { name: 'San Maríno', code: 'SM', dialCode: '+378' },
    { name: 'Svätý Tomáš a Princov ostrov', code: 'ST', dialCode: '+239' },
    { name: 'Saudská Arábia', code: 'SA', dialCode: '+966' },
    { name: 'Senegal', code: 'SN', dialCode: '+221' },
    { name: 'Srbsko', code: 'RS', dialCode: '+381' },
    { name: 'Seychely', code: 'SC', dialCode: '+248' },
    { name: 'Sierra Leone', code: 'SL', dialCode: '+232' },
    { name: 'Singapur', code: 'SG', dialCode: '+65' },
    { name: 'Slovinsko', code: 'SI', dialCode: '+386' },
    { name: 'Šalamúnove ostrovy', code: 'SB', dialCode: '+677' },
    { name: 'Somálsko', code: 'SO', dialCode: '+252' },
    { name: 'Južná Afrika', code: 'ZA', dialCode: '+27' },
    { name: 'Španielsko', code: 'ES', dialCode: '+34' },
    { name: 'Srí Lanka', code: 'LK', dialCode: '+94' },
    { name: 'Sudán', code: 'SD', dialCode: '+249' },
    { name: 'Surinam', code: 'SR', dialCode: '+597' },
    { name: 'Švédsko', code: 'SE', dialCode: '+46' },
    { name: 'Švajčiarsko', code: 'CH', dialCode: '+41' },
    { name: 'Sýria', code: 'SY', dialCode: '+963' },
    { name: 'Tadžikistan', code: 'TJ', dialCode: '+992' },
    { name: 'Tanzánia', code: 'TZ', dialCode: '+255' },
    { name: 'Thajsko', code: 'TH', dialCode: '+66' },
    { name: 'Togo', code: 'TG', dialCode: '+228' },
    { name: 'Tonga', code: 'TO', dialCode: '+676' },
    { name: 'Trinidad a Tobago', code: 'TT', dialCode: '+1868' },
    { name: 'Tunisko', code: 'TN', dialCode: '+216' },
    { name: 'Turecko', code: 'TR', dialCode: '+90' },
    { name: 'Turkménsko', code: 'TM', dialCode: '+993' },
    { name: 'Tuvalu', code: 'TV', dialCode: '+688' },
    { name: 'Uganda', code: 'UG', dialCode: '+256' },
    { name: 'Ukrajina', code: 'UA', dialCode: '+380' },
    { name: 'Spojené arabské emiráty', code: 'AE', dialCode: '+971' },
    { name: 'Spojené kráľovstvo', code: 'GB', dialCode: '+44' },
    { name: 'Uruguaj', code: 'UY', dialCode: '+598' },
    { name: 'USA', code: 'US', dialCode: '+1' },
    { name: 'Uzbekistan', code: 'UZ', dialCode: '+998' },
    { name: 'Vanuatu', code: 'VU', dialCode: '+678' },
    { name: 'Venezuela', code: 'VE', dialCode: '+58' },
    { name: 'Vietnam', code: 'VN', dialCode: '+84' },
    { name: 'Západná Sahara', code: 'EH', dialCode: '+212' },
    { name: 'Jemen', code: 'YE', dialCode: '+967' },
    { name: 'Zambia', code: 'ZM', dialCode: '+260' },
    { name: 'Zimbabwe', code: 'ZW', dialCode: '+263' }
];
